name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ensure this matches your Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        npm run build  # or whatever build command you use

    - name: Deploy to Firebase
      uses: wzieba/Firebase-Action@v2
      with:
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
